---
name: cf-mysql-java-broker-cluster
director_uuid: 53e56169-85eb-428f-b2ef-04caf08525bb
releases:
- name: cf-mysql-java-broker
  version: latest
compilation:
  workers: 3
  network: cf-mysql-java-broker-network
  reuse_compilation_vms: false
  cloud_properties:
    name: random
update:
  canaries: 1
  max_in_flight: 4
  canary_watch_time: 10000-30000
  update_watch_time: 10000-30000
resource_pools:
- name: common
  network: cf-mysql-java-broker-network
  size: 2
  stemcell:
    name: bosh-stemcell
    version: latest
  cloud_properties:
    name: random
networks:
- name: cf-mysql-java-broker-network
  subnets:
<% (0..28).each_with_index do |i| %>
  - range: 10.244.3.<%= i*4 %>/30
    reserved:
      - 10.244.3.<%= i*4 + 1 %>
    static:
      - 10.244.3.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>
<% (29..61).each_with_index do |i| %>
  - range: 10.244.3.<%= i*4 %>/30
    reserved:
      - 10.244.3.<%= i*4 + 1 %>
    cloud_properties:
      name: random
<% end %>
<% (62..63).each_with_index do |i| %>
  - range: 10.244.3.<%= i*4 %>/30
    reserved:
      - 10.244.3.<%= i*4 + 1 %>
    static:
      - 10.244.3.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>
jobs:
- name: mysql
  template: mysql
  instances: 1
  resource_pool: common
  networks:
  - name: cf-mysql-java-broker-network
    static_ips:
    - 10.244.3.22
- name: mysql_broker
  template: mysql_broker
  instances: 1
  resource_pool: common
  networks:
  - name: cf-mysql-java-broker-network
    static_ips:
    - 10.244.3.14    
properties:
  mysql: 
    admin_password: root
    host: 10.244.3.22
    port: 3306    
