--- 
mysql/mysql-5.6.13.tar.gz:
  object_id: 13e8d446-fe4f-4b60-aa74-7446e60ca3dc
  sha: !binary |-
    MDZlMWQ4NTZjZmIxZjk4ODQ0ZWY5MmFmNDdkNGY0ZjcwMzZlZjI5NA==
  size: 35951160
java/jre-7u4-linux-x64.tar.gz:
  object_id: ffa428af-7b75-4468-b50c-7dedafa5f99f
  sha: !binary |-
    MTEwOGQxNzQ0YmFhNzNiZjZjYWEyYWRmOTY1ZDBmNDg5ZWExZWY2MA==
  size: 32771159

