---
mysql/mysql-5.6.13.tar.gz:
  object_id: ac7ff227-e7ae-41aa-969a-77dc76c3024c
  sha: !binary |-
    MDZlMWQ4NTZjZmIxZjk4ODQ0ZWY5MmFmNDdkNGY0ZjcwMzZlZjI5NA==
  size: 35951160
java/jre-7u4-linux-x64.tar.gz:
  object_id: 89ae42dc-a3d1-4c2a-89db-d91ba18afcbd
  sha: !binary |-
    MTEwOGQxNzQ0YmFhNzNiZjZjYWEyYWRmOTY1ZDBmNDg5ZWExZWY2MA==
  size: 32771159
